### PR TITLE
Fixes in bubble.py

### PR DESCRIPTION
**Pull request by jyotika19**
Few edits in bubble.py. Resolved out of bound error and made changes while function call.

email id: jyotikam@iitbhilai.ac.in
college-id: 11940540

### CODE REVIEW

**Comment by jyotika19** [comment]
Changed quick sort into randomized-quick sort, fixed minor bugs
 
email id: jyotikam@iitbhilai.ac.in
college-id: 11940540

**Comment by KShivendu** [comment]
You are only allowed to do one task for each type. Both of these are of type-4. Finish the three other types mentioned in the README

**Comment by jyotika19** [comment]
Removed last commit, has only one task

email id: jyotikam@iitbhilai.ac.in
college-id: 11940540

**Comment by KShivendu** [comment]
LGTM.

**Pull request merged**
